[workspace]
members = ["src/xolo/cli/rust/xolo_cli",
    "src/xolo/core/rust/xolo_core",

]
resolver = "3"

# Central optimization
[profile.release]
opt-level = 3
lto = true

[package]
version="0.1.0-a0"
