project = "xolo-pipeline"
tag_prefix = "v"
ignore_merge_commits = true

[[version_files]]
path = "pyproject.toml"
pattern = 'version = "$version"'

[[version_files]]
path = "Cargo.toml"
pattern = 'version = "$version"'

[changelog]
path = "CHANGELOG.md"
template = "remote" 
remote = "github.com"
repository = "xolo-pipeline"
owner = "xololab"

[commit_types]
feat = { version_update = "minor", changelog_title = "ğŸš€ Features" }
fix = { version_update = "patch", changelog_title = "ğŸ› Bug Fixes" }
docs = { version_update = "patch", changelog_title = "ğŸ“– Documentation" }
chore = { changelog_title = "âš™ï¸ Maintenance" }
perf = { version_update = "patch", changelog_title = "âš¡ Performance" }