tag_prefix = "v"
ignore_merge_commits = true
skip_ci = "[skip ci]"

[commit_types]
feat = { version_update = "minor", changelog_title = "ğŸš€ Features" }
fix = { version_update = "patch", changelog_title = "ğŸ› Bug Fixes" }
perf = { version_update = "patch", changelog_title = "âš¡ Performance" }
refactor = { changelog_title = "ğŸ› ï¸ Refactors" }
docs = { changelog_title = "ğŸ“– Documentation" }
chore = { changelog_title = "âš™ï¸ Maintenance" }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "xolo-pipeline"
owner = "xololab by Ronny Ascencio"

[packages.xolo-pipeline]
path = "."
pre_bump_hooks = [
    "sed -i 's/^version = \".*\"/version = \"{{version}}\"/' pyproject.toml",
    "sed -i 's/^version = \".*\"/version = \"{{version}}\"/' Cargo.toml",
    "cargo fetch"
]
post_bump_hooks = [
    
]