# cog.toml
tag_prefix = "v"
ignore_merge_commits = true
skip_ci = "[skip ci]"

[commit_types]
feat = { version_update = "minor", changelog_title = "ğŸš€ Features" }
fix = { version_update = "patch", changelog_title = "ğŸ› Bug Fixes" }
refactor = { changelog_title = "ğŸ› ï¸ Refactors" }
perf = { version_update = "patch", changelog_title = "âš¡ Performance" }
docs = { changelog_title = "ğŸ“– Documentation" }
chore = { changelog_title = "âš™ï¸ Maintenance" }

[changelog]
path = "CHANGELOG.md"
authors = []

[packages.xolo-pipeline]
path = "."
# Los hooks de abajo actualizan la versiÃ³n en tus archivos .toml automÃ¡ticamente
pre_bump_hooks = [
    "sed -i 's/^version = \".*\"/version = \"{{version}}\"/' pyproject.toml",
    "sed -i 's/^version = \".*\"/version = \"{{version}}\"/' Cargo.toml"
]
