[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xolo-pipeline"
version = "0.1.0"
description = "VFX/animation pipeline for freelancers "
authors = [{name = "Ronny Ascencio"}]
readme = "README.md"
requires-python = ">=3.11"


[tool.hatch.build.targets.sdist]
include = ["cli/**/*", "core/**/*", "dcc/**/*", "tests/**/*", "config.yaml"]

[tool.hatch.build.targets.wheel]
include = ["cli/**/*", "core/**/*", "dcc/**/*", "tests/**/*", "config.yaml"]
