[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xolo-pipeline"
version = "0.1.0a12"
description = "Open source VFX/Animation pipeline for freelancers and small studios."
authors = [{ name = "Ronny Ascencio" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"

dependencies = [
    "typer>=0.12",
    "pyyaml>=6.0",
    "rich>=13.7",
    "platformdirs==4.5.1",
    "requests>=2.32",
    "typing>=3.10.0.0",
    "pathlib>=1.0.1",
    "pyside6>=6.10.1",
    "pydantic>=2.12.5",
]

[project.scripts]
xolo = "src.xolo.cli.python.main:app"

[tool.hatch.build.targets.wheel]
packages = [
    "cli",
    "core",
    "gui",
    "dcc"
]

[dependency-groups]
dev = [
    "build>=1.3.0",
    "commitizen>=4.10.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0a12"
tag_format = "v$version"
version_files = ["pyproject.toml:version"]
major_version_zero = true
update_changelog_on_bump = true
changelog_incremental = true
change_type_order = ["Feat", "Fix", "Docs", "Style", "Refactor", "Perf", "Test"]
change_type_map = { "feat" = "Features", "fix" = "Bug Fixes", "perf" = "Performance Improvements", "docs" = "Documentation" }
