[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xolo-pipeline"
version = "0.0.1"
description = "Open source VFX/Animation pipeline for freelancers and small studios."
authors = [{ name = "Ronny Ascencio" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"

dependencies = [
    "typer>=0.12",
    "pyyaml>=6.0",
    "rich>=13.7",
    "platformdirs==4.5.1",
    "requests>=2.32",
    "typing>=3.10.0.0",
    "pathlib>=1.0.1",
    "pyside6>=6.10.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "black>=24.0",
    "ruff>=0.5.0",
    "mypy>=1.10.0"
]

[project.scripts]
xolo = "cli.xolo_cli.main:app"

[tool.hatch.build.targets.wheel]
packages = [
    "cli",
    "core",
    "gui",
    "dcc"
]

[tool.pyright]
venvPath = "."
venv = ".venv"
