[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xolo-pipeline"
version = "0.1.0"
description = "VFX/animation pipeline for freelancers "
authors = [{name = "Ronny Ascencio"}]
readme = "README.md"
requires-python = ">=3.11, <4.0"
dependencies = [

]


[project.optional-dependencies]
docs = ["mkdocs"]

[dependency-groups]
dev = [
  "typer>=0.19.2",
  "pytest>=7.0",
  "ruff>=0.1",
  "ty",
  "pyside2>=5.15.2.1",
  "pyside6>=6.10.0",
]
lint = [
  "ruff"
]

[project.scripts]
xolo = "cli.main:app"



[tool.hatch.envs.dev]
skip-install = true
scripts = { test = "pytest", lint = "ruff check ." }


[tool.hatch.build.targets.wheel]
include = ["cli/**/*", "core/**/*", "dcc/**/*", "tests/**/*", "config.yaml"]

[tool.uv.workspace]
members = [
    "xolo-desktop",
    "core/xolo_core",
    "gui",
]
