[project]
name = "xolo-nuke"
version = "0.1.0"
requires-python = "==3.11.*"
description = "Integrations / plugins for Nuke 16.x"
dependencies = [
  "xolo-pipeline @ {root}/../..",
  "PySide6"
]

[dependency-groups]
dev = ["pytest", "ruff"]
