[package]
name = "xolo_cli"
<<<<<<< HEAD
version = "0.1.0a0"
=======
version = "0.1.0-a0"
>>>>>>> 5661196 (chore: reset environment and update pipeline)
edition = "2024"

[dependencies]
clap = "4.5.53"
dialoguer = "0.12.0"
