[project]
name = "xolo-blender"
version = "0.1.0"
requires-python = "==3.11.*"
description = "Integrations / addons for Blender 4.5"
dependencies = [
  "xolo-pipeline @ {root}/../..",
]

[dependency-groups]
dev = ["pytest", "ruff"]
